### ISSUE TITLE
Dart/Flutter packages task list

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/breez-sdk-liquid#146]
- [x] Add README's on
  - how to locally build & generate bindings,
  - how to install Dart or Flutter package,
  - how to run Flutter example project both on Android & iOS
- [x] Apply rename changes
- [x] Medium Priority: Create a separate podspec to use Flutter iOS package locally(_distribute the XCFramework alongside the library directly_)
- [ ] Low Priority: Web support via Wasm
- [ ] Low Priority: Fix build for windows targets
  - #169
