### ISSUE TITLE
Notification Plugin

### ISSUE THREAD

**Issue by dangeross** [breez/breez-sdk-liquid#444]
Notifications
- [x] https://github.com/breez/notify/pull/13
- [ ] https://github.com/breez/breez-lnurl/pull/7

SDK
- [x] https://github.com/breez/breez-sdk-liquid/pull/410
- [x] https://github.com/breez/breez-sdk-liquid/pull/440
- [x] https://github.com/breez/breez-sdk-liquid/pull/443
- [x] https://github.com/breez/breez-sdk-liquid/pull/433
- [x] https://github.com/breez/breez-sdk-liquid/pull/436

Docs
- [ ] https://github.com/breez/breez-sdk-liquid-docs/pull/22

Misty Breez
- [x] https://github.com/breez/misty-breez/pull/150
- [x] https://github.com/breez/misty-breez/pull/151
