### ISSUE TITLE
Regtest end-to-end test suite 

### ISSUE THREAD

**Issue by danielgranhao** [breez/breez-sdk-liquid#635]
We should explore the possibility of running end-to-end tests on regtest. These would likely be time-consuming to run, but that's fine if we choose wisely when to run them. 

It should be possible to set up all of the SDK's runtime dependencies (Bitcoin, Liquid, Lightning, Swapper) locally, so I don't see any reason not to have this.

Progress: 

- [x] Support regtest in SDK: #707 
- [x] Set up a regtest environment: #707 
- [x] Create guide for how to use regtest setup (e.g. how to send and receive the different payment types): #811
- [x] Develop tests: #816 
- [x] Decide when to run them and configure CI accordingly: #816
- [ ] Add support for Wasm and run end-to-end tests in browser #846
